//
//  FakeBrew.swift
//  BrewUITests
//

import BrewUITestContract
import Foundation

/// Builds a deterministic stand-in for `brew`, plus the fixture tree it reads.
///
/// The app spawns it through the real `BrewCommandService`, so `Process`, pipes, the line-splitting
/// drain and exit handling all stay under test. It runs directly rather than through a login shell,
/// so `$@` is exactly the brew subcommand argv.
///
/// Nothing here touches the filesystem; the tree travels as data (see ``BrewUITestingFixturePayload``).
nonisolated enum FakeBrew {
    static func payload(for scenario: BrewUITestScenario) -> BrewUITestingFixturePayload {
        let fixtures = ScenarioFixtures.fixtures(for: scenario)
        var files: [String: Data] = [:]

        for (name, contents) in fixtures.brewFiles {
            files["\(scenario.rawValue)/brew/\(name)"] = contents
        }
        for (name, contents) in fixtures.httpFiles {
            files["\(scenario.rawValue)/http/\(name)"] = contents
        }

        // No executable at all, so the app's locator throws rather than resolving something absent.
        guard scenario != .brewNotFound else {
            return BrewUITestingFixturePayload(files: files, executable: nil)
        }

        files[executableName] = Data(dispatcher.utf8)
        return BrewUITestingFixturePayload(files: files, executable: executableName)
    }

    private static let executableName = "fake-brew"

    /// The dispatcher is a lookup table, not a `case` over subcommands: every `brew` invocation is
    /// answered the same way — stdout file, stderr file, exit-code file, all optional — so adding a
    /// command to a scenario is adding a file, never editing this script.
    ///
    /// | file | meaning |
    /// | --- | --- |
    /// | `<argv>.stdout` | written to stdout |
    /// | `<argv>.stderr` | written to stderr |
    /// | `<argv>.exitcode` | exit status; defaults to 0 |
    /// | `<argv>.next-info` | on success, becomes the answer to every later `brew info` |
    ///
    /// `<argv>` is the argument vector joined with `_`, e.g. `install_--formula_ripgrep`. `.next-info`
    /// is how a stateless script models "the world changed" — without it, an uninstalled package would
    /// still be listed by the reconcile that follows the run.
    private static let dispatcher = """
    #!/bin/bash
    # fake-brew — deterministic stand-in for the Homebrew CLI. Generated by BrewUITests/FakeBrew.swift.
    set -u

    scenario_dir="${BREW_UITEST_FIXTURES:?}/${BREW_UITEST_SCENARIO:?}/brew"
    state_dir="${BREW_UITEST_FIXTURES}/${BREW_UITEST_SCENARIO}/state"
    key="$(IFS=_; echo "$*")"
    base="${scenario_dir}/${key}"

    # A previous mutating run may have replaced this command's answer.
    stdout_file="${base}.stdout"
    if [[ -f "${state_dir}/${key}.stdout" ]]; then
        stdout_file="${state_dir}/${key}.stdout"
    fi

    if [[ ! -f "${stdout_file}" && ! -f "${base}.stderr" ]]; then
        echo "fake-brew: no fixture for 'brew $*'" >&2
        echo "fake-brew: looked for ${stdout_file}" >&2
        exit 64
    fi

    if [[ -f "${stdout_file}" ]]; then
        cat "${stdout_file}"
    fi
    if [[ -f "${base}.stderr" ]]; then
        cat "${base}.stderr" >&2
    fi

    status=0
    if [[ -f "${base}.exitcode" ]]; then
        status="$(cat "${base}.exitcode")"
    fi

    if [[ "${status}" -eq 0 && -f "${base}.next-info" ]]; then
        mkdir -p "${state_dir}"
        cp "${base}.next-info" "${state_dir}/\(ScenarioFixtures.installedInfoKey).stdout"
    fi

    exit "${status}"
    """
}
