name: Actionlint

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint GitHub workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color -shellcheck=
